In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from db.dbQueryCorpus import DBQueryCorpus
from config.sConstants import SConstants
db = DBQueryCorpus()
# db.closeConnection()

Mysql database successfuly connected

In [6]:
db.updateTopicTable('dbs_topics')
# db.updateNegReasonTable('dbs_n_reasons')
# db.updateAllKeywordsTable('dbs_allKeywords')
# db.updatePosReasonTable(SConstants.table.pReason)

query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('debit card')
..Exception message: (1062, "Duplicate entry 'debit card' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('transection')
..Exception message: (1062, "Duplicate entry 'transection' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('login')
..Exception message: (1062, "Duplicate entry 'login' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('dashboard')
..Exception message: (1062, "Duplicate entry 'dashboard' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('interest')
..Exception message: (1062, "Duplicate entry 'interest' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('internet')
..Exception message: (1062, "Duplicate entry 'internet' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('speed')
..Exception message: (1062, "Duplicate entry 'speed' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('account')
..Exception message: (1062, "Duplicate entry 'account' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('another bank')
..Exception message: (1062, "Duplicate entry 'another bank' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('atm')
..Exception message: (1062, "Duplicate entry 'atm' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('dbs')
..Exception message: (1062, "Duplicate entry 'dbs' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('balance')
..Exception message: (1062, "Duplicate entry 'balance' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('security')
..Exception message: (1062, "Duplicate entry 'security' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('biometric')
..Exception message: (1062, "Duplicate entry 'biometric' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('look')
..Exception message: (1062, "Duplicate entry 'look' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('cardit card')
..Exception message: (1062, "Duplicate entry 'cardit card' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('charge')
..Exception message: (1062, "Duplicate entry 'charge' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('kyc')
..Exception message: (1062, "Duplicate entry 'kyc' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('app')
..Exception message: (1062, "Duplicate entry 'app' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('version')
..Exception message: (1062, "Duplicate entry 'version' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('debit card')
..Exception message: (1062, "Duplicate entry 'debit card' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('debit cards')
..Exception message: (1062, "Duplicate entry 'debit cards' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('customer care')
..Exception message: (1062, "Duplicate entry 'customer care' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('transfer')
..Exception message: (1062, "Duplicate entry 'transfer' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('upi')
..Exception message: (1062, "Duplicate entry 'upi' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('sign up')
..Exception message: (1062, "Duplicate entry 'sign up' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('signup')
..Exception message: (1062, "Duplicate entry 'signup' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('customer service')
..Exception message: (1062, "Duplicate entry 'customer service' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('postal code')
..Exception message: (1062, "Duplicate entry 'postal code' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('international transactions')
..Exception message: (1062, "Duplicate entry 'international transactions' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('international transaction')
..Exception message: (1062, "Duplicate entry 'international transaction' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('signup')
..Exception message: (1062, "Duplicate entry 'signup' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('deals and offers')
..Exception message: (1062, "Duplicate entry 'deals and offers' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('offers')
..Exception message: (1062, "Duplicate entry 'offers' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('offer')
..Exception message: (1062, "Duplicate entry 'offer' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('back option')
..Exception message: (1062, "Duplicate entry 'back option' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('update')
..Exception message: (1062, "Duplicate entry 'update' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('ifsc')
..Exception message: (1062, "Duplicate entry 'ifsc' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('transaction')
..Exception message: (1062, "Duplicate entry 'transaction' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('transactions')
..Exception message: (1062, "Duplicate entry 'transactions' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('physical card')
..Exception message: (1062, "Duplicate entry 'physical card' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('permission')
..Exception message: (1062, "Duplicate entry 'permission' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('withdrawl')
..Exception message: (1062, "Duplicate entry 'withdrawl' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('netbanking')
..Exception message: (1062, "Duplicate entry 'netbanking' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('otp')
..Exception message: (1062, "Duplicate entry 'otp' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('service charge')
..Exception message: (1062, "Duplicate entry 'service charge' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('banking')
..Exception message: (1062, "Duplicate entry 'banking' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('bank')
..Exception message: (1062, "Duplicate entry 'bank' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('bank account')
..Exception message: (1062, "Duplicate entry 'bank account' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('mutual funds')
..Exception message: (1062, "Duplicate entry 'mutual funds' for key 'topic'")
--- failed --
query is:  INSERT INTO `dbs_topics` (`topic`) VALUES ('mutual fund')
..Exception message: (1062, "Duplicate entry 'mutual fund' for key 'topic'")
--- failed --